### ISSUE TITLE
Test supported S3 implementations

### ISSUE THREAD

**Issue by gedw99** [stv0g/gose#19]
This looks very well designed and handles many edge cases others ignore - great work 

i was wondering is we could also support minio and google cloud storage .. I have not texted it yet but it would be useful to know if you have ?

**Comment by stv0g** [comment]
Hi @gedw99,

Gose should support all S3-compliant backends. We use some slightly advanced S3-features like multi-part uploads and metadata fields. However, those are today supported by all major S3 implementations.

> I have not texted it yet but it would be useful to know if you have ?

No, I havn't tested it yet myself.

**Comment by stv0g** [comment]
Lets add some integration tests for the most prominent S3 implementations:

- [ ] Ceph RadosGW
- [ ] Minio
- [ ] Amazon AWS S3
- [ ] Google Cloud Storage S3 / XML API
- [ ] Digitaloceans Spaces
- [ ] Backblaze B2 S3 API

**Comment by stv0g** [comment]
Also related to #14

**Comment by gedw99** [comment]
Hey @stv0g thanks for considering my request.

Wow you also support multi-part uploads and metadata fields.. This is really better than i thought :)

I will be trying more of this out.

**Comment by stv0g** [comment]
The nice thing about multiparts uploads is, that they are resumable. An upload aborted half way, will only upload the missing pieces if retried another time.

**Comment by gedw99** [comment]
> The nice thing about multiparts uploads is, that they are resumable. An upload aborted half way, will only upload the missing pieces if retried another time.

very much needed for large files... :)

How is this aspect currently designed ? I have 2 scenarios that i am needing: 
- the client holds the file, and then uploads to the server in chunks. When the client is back online it resumes.
- the Server gets the full file and then uploads to s3 in chunks ?

**Comment by stv0g** [comment]
Both up and downloads are always directly accessing the S3 server. Never Gose directly. This keeps bandwidth costs low and scales as good as your S3 provider scales.

The reassembly of chunks is performed by the S3 server as multipart uploads are a feature of the S3 API not Gose specifically.

**Comment by gedw99** [comment]
Ah ok I get it. Pretty cool how gose is not in the data path. 

i think I will try it with minio locally .

I guess gose being in the control path listend to notifications from minio via its web hook ?



I might try to integrate with https://github.com/hack-pad/hackpadfs as I feel there is a lot of synergy . Have a look if your curious

**Comment by stv0g** [comment]
> I guess gose being in the control path listend to notifications from minio via its web hook ?

Not exactly, notifications are not required here.

It's not always easy to persist everything in S3. Stuff like download counters per file are difficult since S3 provides no atomicity guarantees for object operations.

I am considering to add optional support for a cache like Redis to manage stuff like counters.

**Comment by gedw99** [comment]
> Not exactly, notifications are not required here.

Am confused then. If gose is not in the data path, then how can it know when an upload completes, unless it taps into the notifications that the s3 produces and gose subscribed to ?    The reason i ask if just to understand gose as its quite nice approach.

> I am considering to add optional support for a cache like Redis to manage stuff like counters.

I guess you bring this up as a way of tracking uploads and hence notification of when something succeeds or fails ?

**Comment by stv0g** [comment]
The whole upload is currently orchestrated by the browser (JS code) which first creates a MPU (Multi Part Upload) session via the Gose backend. As a response it receives upload URLs to which the parts are uploaded to the S3 server. Finally the JS code completes the MPU with a request to the Gose backend.

So the whole process is managed by the client. E.g. the client knows when the parts have been uploaded. However the final MPU completion will fail if not all parts are present.

**Comment by gedw99** [comment]
Thanks for the info. It all makes sense now.

I need an s3 file explorer where I can show the folders and files .

It needs to sync the files on s3 with the client .

the hackpadfs repo will help because it has a file api for both browser ( via index db ) and s3. 



If your interested is something like this let me know. It will be golang compiled to wasm with a js api. I find it easier to use golang rather than js .

**Comment by gedw99** [comment]
I am going to close this as we got side tracked..
