### ISSUE TITLE
Using "Server" HTTP header is not a reliable mechanism for detecting S3 implementation

### ISSUE THREAD

**Issue by stv0g** [stv0g/gose#26]
> So, I fixed the final issue with the final checksum mismatch and tested it with the included `docker-compose.yml` file.
> 
> Let me know if works for you :)

got yet another issue i'm afraid, since i have my domain routed through cloudflare gose now thinks i'm using cloudflare s3 and not minio

_Originally posted by @LeagueRaINi in https://github.com/stv0g/gose/issues/23#issuecomment-1152749492_

**Comment by stv0g** [comment]
I started to dig around a bit deeper and found here the RFC which specifies the `Server` header: [RFC2616 (section 14.38)](https://datatracker.ietf.org/doc/html/rfc2616#section-14.38):

> The Server response-header field contains information about the software used by the **origin** server to handle the request.

It explicitly mentions:

> If the response is being forwarded through a proxy, the proxy
> application MUST NOT modify the Server response-header. Instead, it
> SHOULD include a Via field (as described in [section 14.45](https://datatracker.ietf.org/doc/html/rfc2616#section-14.45)).

So I think Cloudflare is not complying to the RFC here.

@LeagueRaINi Can you check if your can disable this behaviour in your Cloudfare setup?

**Comment by LeagueRaINi** [comment]
not sure where i would change that in the cloudflare control panel to be honest, easiest would probably to allow overwriting the s3 server impl in the config?

**Comment by stv0g** [comment]
Oh yeah, thats probably the simplest solution. I will implement this.

**Comment by stv0g** [comment]
Hi @LeagueRaINi

I've added some new settings:

```env
GOSE_IMPLEMENTATION = MinIO
```

which implies the following settings which disable unsupported features by MinIO:

```env
GOSE_SETUP_CORS = false
GOSE_SETUP_ABORT_INCOMPLETE_UPLOADS = 0
```

I havn`t tested the code so feedback would be appreciated :)

**Comment by LeagueRaINi** [comment]
looks like everything is working now thanks :)
